# Generated by Django 4.1.3 on 2023-01-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_ambiente', models.CharField(choices=[('PT', 'Planta'), ('CNT', 'Contratista')], default='PT', max_length=11)),
                ('capacidad', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CC DIG', 'Cedula digital')], default='CC', max_length=6)),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'db_table': 'ambiente',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tipo_competencia', models.CharField(choices=[('G', 'Generica'), ('E', 'Especifica')], default='G', max_length=1)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'db_table': 'competencia',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'programa',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'TipoUsuario',
                'verbose_name_plural': 'TiposUsuario',
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('tipo_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.tipousuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['login'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('programas', models.ManyToManyField(to='Academico.programa')),
            ],
            options={
                'verbose_name': 'PeriodoAcademico',
                'verbose_name_plural': 'PeriodosAcademicos',
                'db_table': 'periodo_academico',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('docente', models.CharField(choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miercoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes'), ('Sab', 'Sabado')], default='Lun', max_length=9)),
                ('f_horaria', models.TimeField()),
                ('ambiente', models.TimeField()),
                ('horas_sem', models.PositiveIntegerField()),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.competencia')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miercoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes'), ('Sab', 'Sabado')], default='Lun', max_length=9)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('horas_dia', models.PositiveIntegerField()),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.competencia')),
            ],
            options={
                'verbose_name': 'FranjaHoraria',
                'verbose_name_plural': 'FranjasHorarias',
                'db_table': 'franja_horaria',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('identificacion', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CC DIG', 'Cedula digital')], default='CC', max_length=6)),
                ('tipo_docente', models.CharField(choices=[('T', 'Tecnico'), ('P', 'Profesional')], default='Tecnico', max_length=11)),
                ('tipo_contrato', models.CharField(choices=[('PT', 'Planta'), ('CNT', 'Contratista')], default='PT', max_length=11)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.area')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
                'ordering': ['apellido_paterno', '-apellido_materno'],
            },
        ),
        migrations.AddField(
            model_name='competencia',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.programa'),
        ),
    ]
