# Generated by Django 4.1.3 on 2023-01-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='programa',
        ),
        migrations.AddField(
            model_name='programa',
            name='competencias',
            field=models.ManyToManyField(to='Academico.competencia'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='capacidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='tipo_ambiente',
            field=models.CharField(choices=[('V', 'Virtual'), ('P', 'Presencial')], default='V', max_length=11),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='ubicacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horario',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.ambiente'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.docente'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='f_horaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.franjahoraria'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.periodoacademico'),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
