# Generated by Django 3.2.13 on 2023-01-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_remove_competencia_programa_programa_competencias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franjahoraria',
            name='competencia',
        ),
    ]
