# Generated by Django 3.2.13 on 2023-01-23 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_auto_20230120_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.competencia'),
        ),
    ]
