# Generated by Django 3.2.13 on 2023-01-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_horario_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franjahoraria',
            name='dia',
            field=models.DateField(),
        ),
    ]
