# Generated by Django 3.2.13 on 2023-01-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_alter_franjahoraria_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franjahoraria',
            name='horas_dia',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
