# Generated by Django 3.2.13 on 2023-01-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0007_alter_franjahoraria_horas_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='horas_sem',
        ),
    ]
